## Original script generated by R van Cruchten
## Slight modifications by D van As for publication purposes


## Load libraries
library(tidyverse)   #V 1.3.1
library(ggplot2)     #V 3.3.3
library(ggpubr)      #V 0.4.0
library("gridExtra") #V 2.3

## Load datasets
# a file with all changes in outcome measures, corrected for direction. This file is generated in: outcomes_and_corrections.R
load(file = "dOutcomes_corrected.RDATA")

# load an R file which contains all measured outcomes, separated by their type (see also Fig 1). This file is generated in: outcomes_and_corrections.R
load(file = "outcome_types.RData")

# load a file with the metadata of the samples. Due to privacy considerations, this is only available via restricted access on the EGA (study ID EGAS00001005830). 
# The column "visit" should be generated by the user based on the "description" column in the EGA metadata. (before CBT == V2, after CBT == V4) 
load(file = "samples.RDATA")

## Boxplot
#scale the outcomes
df <- t(scale(t(dOutcomes_corrected), center = FALSE, scale = apply(t(dOutcomes_corrected), 2, sd, na.rm = TRUE)))
df <- cbind(outcome = rownames(df),df)
df <- data.frame(df) %>% pivot_longer(cols = c(colnames(df))[-1], names_to = "PatientID", values_to = "outcome_change")

# separate classes of outcomes, provide color coding and label non-relevant info in dOutcomes_corrected with "error"
df$type <- ifelse(df$outcome == "DM1ActivC", "purple",
                  ifelse(df$outcome %in% outcome_types[["Compound_scores"]], "red", 
                         ifelse(df$outcome %in% outcome_types[["Physical"]], "blue",
                                ifelse(df$outcome %in% outcome_types[["Fatigue"]], "black",
                                       ifelse(df$outcome %in% outcome_types[["Cognitive"]], "grey43",
                                              ifelse(df$outcome %in% outcome_types[["Pain_depr,_soc,_att."]], "grey43",
                                                     "error"))))))

# DM1ActivC as square
df$shape <- ifelse(df$outcome == "DM1ActivC", 15, 
                   16)

# remove non-relevant outcome measures
df <- df[!df[,"type"] == "error",]

# Prepare ordering by change in DM1ActivC
df <- cbind(df, clust_order = c(rep(dOutcomes_corrected["DM1ActivC",], k=3, 22)))

# Turn values into numeric
df$outcome_change <- as.numeric(df$outcome_change)

# Reverse the order so that DM1ActivC is plotted on top
df <- df[rev(1:nrow(df)),]

# insert scaled mean outcomes from samples table, arbitrarily from V2
means <- as.numeric(samples[grep("V2", rownames(samples)),"scaled_mean_outcome"])
names(means) <- samples[grep("V2", rownames(samples)), "PatientID"]
means <- means[order(names(means))]
means <- means[order(dOutcomes_corrected["DM1ActivC",])]

# Plot 
A <- ggplot(df, aes(x=reorder(PatientID, clust_order), y = outcome_change))+
        geom_boxplot(outlier.size = 0, 
                     middle = means, 
                     fatten = 3) +
        geom_point(cex = 2, 
                   col = df$type, 
                   shape = df$shape)+
        geom_hline(yintercept=0, 
                   col = "red")+
        xlab("Patient ID")+
        ylab("Scaled improvement")+
        scale_y_continuous(limits = c(-4.5,4.5), 
                           breaks=seq(-4,4,1), 
                           sec.axis = dup_axis(breaks = derive(), labels = NULL, name = NULL))+
        theme_classic() +
        theme(panel.grid.major.x = element_line(size = 0.25, color = "grey"),
              panel.grid.major.y = element_line(size = 0.25, color = "grey"),
              panel.border = element_rect(colour = "black", fill = NA, size = 0.5),
              axis.text.x = element_text(color = "black", size = 16),
              axis.text.y = element_text(color = "black", size = 16),
              axis.title.y = element_text(color = "black", size = 18),
              axis.title.x = element_text(color = "black", size = 18),
              plot.margin = margin(c(0.05,0.05,0.05,0.05), unit="cm"))+
        coord_flip()


# Generate custom legend for outcome groups
df$outcome_group <- df$type
df$outcome_group[df$outcome_group == "purple"] <- "DM1-Activ-c"
df$outcome_group[df$outcome_group == "blue"] <- "Physical assessments"
df$outcome_group[df$outcome_group == "grey43"] <- "Cognition and other"
df$outcome_group[df$outcome_group == "black"] <- "Fatigue scores"
df$outcome_group[df$outcome_group == "red"] <- "Quality of Life"


df <- df[order(df$outcome_group),]
my_colors <- c("gray43", "purple", "black", "blue", "red")
B <- ggplot(df, aes(type, outcome, color = outcome_group)) +
  geom_point() +
  scale_color_manual(values = my_colors, name = "Outcome group") +
  theme_bw() +
  guides(colour = guide_legend(override.aes = list(size=5))) +
  theme(
    legend.key.size = unit(1, 'cm'),
    legend.key.height = unit(1, 'cm'),
    legend.title = element_text(size=18),
    legend.text = element_text(size=16)
  )
B <- get_legend(B)
B <- as_ggplot(B)


## Combine plot with legend
gs <- list(A, B)
lay <- rbind(c(1,1,1,1,3),
             c(1,1,1,1,2),
             c(1,1,1,1,3))
plot <- arrangeGrob(grobs = gs, layout_matrix=lay)

ggsave(plot, file ="Fig1_out_het.png", height = 10, width = 15, dpi = 1200, device="png" )





