---
title: "Fig1_outcomes"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
```

## Fig 1

### loading data 
```{r}
load(file = "Z:/Analysis_projects/RvC_recognition_rnaseq_diff_expr/Analyses_rnaseq_recognition/dOutcomes_corrected.RData")
load(file = "Z:/Analysis_projects/RvC_recognition_rnaseq_diff_expr/Analyses_rnaseq_recognition/outcome_types.RData")
load(file = "Z:/Analysis_projects/RvC_recognition_rnaseq_diff_expr/Analyses_rnaseq_recognition/results/mixed_effect_models/htseq_manual/samples.RDATA")

```

### Box plot

```{r}
#scale the outcomes
df <- t(scale(t(dOutcomes_corrected), center = FALSE, scale = apply(t(dOutcomes_corrected), 2, sd, na.rm = TRUE)))
df <- cbind(outcome = rownames(df),df)
df <- data.frame(df) %>% pivot_longer(cols = c(colnames(df))[-1], names_to = "PatientID", values_to = "outcome_change")

# separate classes of outcomes, provide color coding and label non-relevant info in dOutcomes_corrected with "error"
df$type <- ifelse(df$outcome == "DM1ActivC", "purple",
       ifelse(df$outcome %in% outcome_types[["Compound_scores"]], "red", 
       ifelse(df$outcome %in% outcome_types[["Physical"]], "blue",
       ifelse(df$outcome %in% outcome_types[["Fatigue"]], "black",
       ifelse(df$outcome %in% outcome_types[["Cognitive"]], "grey43",
       ifelse(df$outcome %in% outcome_types[["Pain_depr,_soc,_att."]], "grey43",
              "error"))))))

# DM1ActivC as square
df$shape <- ifelse(df$outcome == "DM1ActivC", 15, 
                     16)

# remove non-relevant outcome measures
df <- df[!df[,"type"] == "error",]

# Prepare ordering by change in DM1ActivC
df <- cbind(df, clust_order = c(rep(dOutcomes_corrected["DM1ActivC",], k=3, 22)))

# Turn values into numeric
df$outcome_change <- as.numeric(df$outcome_change)

# Reverse the order so that DM1ActivC is plotted on top
df <- df[rev(1:nrow(df)),]
  
# insert scaled mean outcomes from samples table, arbitrarily from V2
means <- as.numeric(samples[grep("V2", rownames(samples)),"scaled_mean_outcome"])
names(means) <- samples[grep("V2", rownames(samples)), "PatientID"]
means <- means[order(names(means))]
means <- means[order(dOutcomes_corrected["DM1ActivC",])]

# Plot 
print(ggplot(df, aes(x=reorder(PatientID, clust_order), y = outcome_change))+
  geom_boxplot(outlier.size = 0, 
               middle = means, 
               fatten = 3) +
  geom_point(cex = 2, 
             col = df$type, 
             shape = df$shape)+
  geom_hline(yintercept=0, 
             col = "red")+
  xlab("Patient ID")+
  ylab("Scaled improvement")+
  scale_y_continuous(limits = c(-4.5,4.5), 
                     breaks=seq(-4,4,1), 
                     sec.axis = dup_axis(breaks = derive(), labels = NULL, name = NULL))+
  theme_classic() +
  theme(panel.grid.major.x = element_line(size = 0.25, color = "grey"))+
  theme(panel.grid.major.y = element_line(size = 0.25, color = "grey"))+
  theme(panel.border = element_rect(colour = "black", fill = NA, size = 1))+
  coord_flip()
)

ggsave(file = "Z:/Analysis_projects/RvC_recognition_rnaseq_diff_expr/for_paper_counts/Figs_for_paper/Fig1_outcomes.png", height = 6, width = 10)
```
