---
title: "Fig3"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(ggrepel)
library(cowplot)
```

## Fig 3


```{r}
load(file = "Z:/Analysis_projects/RvC_recognition_rnaseq_diff_expr/Analyses_rnaseq_recognition/results/mixed_effect_models/htseq_manual/samples.RDATA")
load(file = "Z:/Analysis_projects/RvC_recognition_rnaseq_diff_expr/for_paper_counts/fits_paper/model_values_all.RData")
load(file = "Z:/Analysis_projects/RvC_recognition_rnaseq_diff_expr/for_paper_counts/fits_paper/v_visit.RDATA")
hgnc_symbol <- read.table("Z:/Analysis_projects/RvC_recognition_rnaseq_diff_expr/Analyses_rnaseq_recognition/metadata/ENSG_geneSymbol2.txt", sep =",", header=TRUE)
```

```{r}
df <- data.frame(p.value = model_values_all[["Visit"]][,"p.val"],
                 FDR = model_values_all[["Visit"]][,"FDR"], 
                 effect = model_values_all[["Visit"]][,"Estimate"])

ggplot(df, aes(x = effect, y = -log10(p.value)))+
      geom_point(size= 1, col = ifelse(df$FDR < 0.05, "black","grey")) +
      geom_label_repel(label = ifelse(model_values_all[["Visit"]][,"ENSG"] %in%  model_values_all[["Visit"]][,"ENSG"][order(model_values_all[["Visit"]][,"p.val"])][1:5], model_values_all[["Visit"]][,"hgnc_symbol"], ""), max.overlaps = 100,  force = 25, color = "black", size = 3, segment.size = 0.25) +
      xlab("Effect size (logCPM/CBT)") +
      ylab("-10log(p-value)") +
      theme(legend.position = "none", 
            aspect.ratio = 4/3)  +
      scale_x_continuous(limits = c(-1.25, 1.25), 
                        breaks = c(seq(-1.25,-0.25,0.5), 0, seq(0.25, 1.25,0.5)) , 
                        labels = c(scales::comma(seq(-1.25,-0.25,0.5), accuracy = c(0.01)), scales::comma(0, accuracy = c(1)), scales::comma(seq(0.25, 1.25,0.5), accuracy = c(0.01))),
                        sec.axis = dup_axis(breaks = derive(), labels = derive(), name = NULL))+
      scale_y_continuous(limits = c(0, 6), 
                         breaks = seq(0, 6, 1),
                         sec.axis = dup_axis(breaks = derive(), labels = derive(), name = NULL))+
      theme_classic()

ggsave(file = "Z:/Analysis_projects/RvC_recognition_rnaseq_diff_expr/for_paper_counts/Figs_for_paper/Fig3_CBTgenes.png", width = 6, height = 8)

# The number of genes with an FDR > 0.05
sum(model_values_all[["Visit"]][,"FDR"] < 0.05)
# of which with a positive correlation
sum(model_values_all[["Visit"]][,"FDR"] < 0.05 & model_values_all[["Visit"]][,"Estimate"] > 0 )
# of which with a negative correlation
sum(model_values_all[["Visit"]][,"FDR"] < 0.05 & model_values_all[["Visit"]][,"Estimate"] < 0 )

#write table with IDs to use for gene enrichment analysis

CBThits <- model_values_all[["Visit"]][model_values_all[["Visit"]][,"FDR"] < 0.05,]
CBThits <- CBThits[rev(order(abs(CBThits[,"Estimate"]))),][1:100,"ENSG"]

write.table(CBThits,
            file = "Z:/Analysis_projects/RvC_recognition_rnaseq_diff_expr/for_paper_counts/cytoscape/CBT_FDR005top100E.csv", 
          quote = FALSE, 
          row.names= FALSE,
          col.names= FALSE
   )
```


```{r}

gene_plots <- list()
for (ENSG_ID in model_values_all[["Visit"]][,"ENSG"][order(model_values_all[["Visit"]][,"p.val"])][1:5]){

df2 <- data.frame(samples[,"Visit"], v[["E"]][ENSG_ID,], samples[,"PatientID"])
names(df2) <- c("Visit","counts","PatientID")
df2 <- df2[order(df2$Visit),]


gene_plots[[ENSG_ID]] <- ggplot(df2,  aes_string(x="Visit", y="counts",group="PatientID")) +    
   ggtitle(paste(hgnc_symbol$hgnc_symbol[hgnc_symbol$ensembl_gene_id==ENSG_ID]))+
   geom_point(col = ifelse(df2$Visit == "V2", "blue", "red")) +
   geom_path(col= "black") + 
   ylab("logCPM") +
   xlab("") +
   theme(aspect.ratio = 4/1)  +
   scale_x_discrete(expand = c(0.1,0), labels = c("Baseline","10 Mo. CBT"))+ 
   scale_y_continuous(sec.axis = dup_axis(breaks = derive(), labels = NULL, name = NULL))+
   theme_classic() +
   theme(panel.grid.major.x = element_line(size = 0.25, color = "grey"))+
   theme(panel.grid.major.y = element_line(size = 0.25, color = "grey"))+
   theme(panel.border = element_rect(colour = "black", fill = NA, size = 1))
}

plots <- plot_grid(plotlist = gene_plots, ncol = 1 )
ggsave(plots, file ="Z:/Analysis_projects/RvC_recognition_rnaseq_diff_expr/for_paper_counts/Figs_for_paper/Fig3B_CBTplots.png", height = 24, width = 6 , dpi = 600)

```