---
title: "Fig1_outcomes"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(corrplot)
```

## Fig 4

### loading data 
```{r}

load(file = "Z:/Analysis_projects/RvC_recognition_rnaseq_diff_expr/for_paper_counts/fits_paper/model_values_all.RData")
load(file = "Z:/Analysis_projects/RvC_recognition_rnaseq_diff_expr/Analyses_rnaseq_recognition/outcome_types.RData")
load(file = "Z:/Analysis_projects/RvC_recognition_rnaseq_diff_expr/Analyses_rnaseq_recognition/corrections_outcomes.RData")
```

### Data prep
```{r}

# create list of all relevant outcome measures
outcomes <- c(unlist(outcome_types), "L5ENMO")

# Extract fixed effect estimates for all measures
estimates <- list()
for (outcome in outcomes){
  estimates[[outcome]] <-  model_values_all[[outcome]]["Estimate"]
  }
estimates <- do.call(cbind, estimates)
colnames(estimates) <- outcomes

# correct outcomes for change in 'positive' direction
estimates_corrected <- list()
for (outcome in outcomes){
  estimates_corrected[[outcome]] <-  as.numeric(corrections[outcome]* estimates[,outcome])
  }
estimates_corrected <- do.call(cbind, estimates_corrected)
colnames(estimates_corrected) <- outcomes

```

## corallelogram
```{r}
# plot correlation plot 
png(file = "Z:/Analysis_projects/RvC_recognition_rnaseq_diff_expr/for_paper_counts/Figs_for_paper/Fig4_outcome_correlations.png", width = 4000, height = 4000, res = 600, pointsize = 20)
corrplot(cor(estimates_corrected), 
         method= "circle", 
         order = "hclust", 
         addrect = 5, 
         rect.lwd = 1,
         cl.cex = 0.4,
         cl.align = "l", 
         tl.col = "black",
         tl.offset = 0.5,
         tl.cex = 0.4
)
dev.off()

```