---
title: "Fig1_outcomes"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(VennDiagram)
library(corrplot)
library(ggplot2)

```

## Fig 5

### loading data 
```{r}

load(file = "Z:/Analysis_projects/RvC_recognition_rnaseq_diff_expr/for_paper_counts/fits_paper/model_values_all.RData")

```

### Data prep
```{r}
int_hits <- model_values_all[["int_CBT_scaled_mean_outcome"]][,"ENSG"][model_values_all[["int_CBT_scaled_mean_outcome"]][,"FDR"] < 0.25]
V2Mode_hits <- model_values_all[["V2Mode"]][,"ENSG"][model_values_all[["V2Mode"]][,"FDR"] < 0.05]
hit_list <- list("Clinical improvement" = int_hits, "CTG repeat" = V2Mode_hits)
```


## A. Venn diagram
```{r}
VennDiagram::venn.diagram(hit_list, 
                          cex = 0.75,
                          category.names = names(hit_list), 
                          cat.dist = 0.03,
                          cat.pos = c(0,0),
                          cat.cex = 0.75,
                          rotation.degree = 180,
                          fill = c("red","blue"), 
                          lwd = 1,
                          resolution =  1200,
                          imagetype = "png",
                          filename = "Z:/Analysis_projects/RvC_recognition_rnaseq_diff_expr/for_paper_counts/Figs_for_paper/Fig5A_venn.png"
                          )
```

## B. scatter plot
```{r}

Repeat <- model_values_all[["V2Mode"]][model_values_all[["V2Mode"]][,"ENSG"] %in% unique(unlist(hit_list)),]
Response <- model_values_all[["int_CBT_scaled_mean_outcome"]][model_values_all[["int_CBT_scaled_mean_outcome"]][,"ENSG"] %in% unique(unlist(hit_list)),]

df <- data.frame(
  Repeat = Repeat[,"Estimate"]*100,
  Response = Response[,"Estimate"],
  both = ifelse(Response[,"FDR"] < 0.25 & Repeat[,"FDR"] < 0.05, "yes","no"))

df <- df[order(df$both),]

ggplot(df,  aes_string(x="Repeat", y="Response")) + 
  geom_point(col = ifelse(df$both == "yes", "purple4", "grey70"), cex = ifelse(df$both == "yes", 0.5, 0.3))+
  ggtitle("")+
  xlab("Association with repeat length (logCPM/100CTG)") + 
  ylab("Interaction effect for response (logCPM/stdev)") +
  geom_hline(yintercept=0, col = "red")+
  geom_vline(xintercept=0, col = "red")+
  scale_y_continuous(breaks = seq(-2.5, 2.5, 0.5), 
                     labels = scales::comma(seq(-2.5, 2.5, 0.5), accuracy = c(0.1)), 
                     limits = c(-2.75, 2.75),
                     sec.axis = dup_axis(breaks = derive(), labels = NULL, name = NULL))+
  scale_x_continuous(breaks = seq(-0.25, 0.25, 0.05), 
                     labels = scales::comma(seq(-0.25, 0.25, 0.05), accuracy = c(0.01)), 
                     limits = c(-0.25,0.25),
                     sec.axis = dup_axis(breaks = derive(), labels = NULL, name = NULL))+
  theme_classic() +
  theme(panel.grid.major.x = element_line(size = 0.25, color = "grey"))+
  theme(panel.grid.major.y = element_line(size = 0.25, color = "grey"))
   


ggsave("Z:/Analysis_projects/RvC_recognition_rnaseq_diff_expr/for_paper_counts/Figs_for_paper/Fig5B_scatter.png", dpi = 600, height = 5, width = 7)

```
Table S2

```{r}
model_values_S1 <- read.csv(file = "Z:/Analysis_projects/RvC_recognition_rnaseq_diff_expr/for_paper_counts/Figs_for_paper/TableS1_effects.csv")

model_values_S2 <- model_values_S1[model_values_S1$ENSG %in% intersect(int_hits,V2Mode_hits),
                                   grep("ENSG|hgnc_symbol|CTGRepeatLength|MeanClinImprov", colnames(model_values_S1))]

write.csv(model_values_S2,          
          quote = FALSE,
          row.names= FALSE,
          file = "Z:/Analysis_projects/RvC_recognition_rnaseq_diff_expr/for_paper_counts/Figs_for_paper/TableS2_effects_105genes.csv"
)
```
