---
title: "Fig1_outcomes"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)

```

## Fig S3

### loading data 
```{r}

load(file = "Z:/Analysis_projects/RvC_recognition_rnaseq_diff_expr/for_paper_counts/fits_paper/model_values_all.RData")
Sznajder_blood <- read.csv(file = "Z:/Analysis_projects/GSE138691/lm_fit_disease_values.csv", sep = " ")
```

### Data prep
```{r}
int_hits <- model_values_all[["int_CBT_scaled_mean_outcome"]][,"ENSG"][model_values_all[["int_CBT_scaled_mean_outcome"]][,"FDR"] < 0.25]
V2Mode_hits <- model_values_all[["V2Mode"]][,"ENSG"][model_values_all[["V2Mode"]][,"FDR"] < 0.05]
hit_list <- list("Clinical improvement" = int_hits, "CTG repeat" = V2Mode_hits)

#remove genes not measureed in Sznajders experiment
overlap_genes <-   intersect(int_hits, V2Mode_hits)[intersect(int_hits, V2Mode_hits) %in%  Sznajder_blood[,"ENSG"]]

model_values_all[["int_CBT_scaled_mean_outcome"]] <- model_values_all[["int_CBT_scaled_mean_outcome"]][model_values_all[["int_CBT_scaled_mean_outcome"]][,"ENSG"] %in% Sznajder_blood[,"ENSG"],]

model_values_all[["int_CBT_scaled_mean_outcome"]] <- model_values_all[["int_CBT_scaled_mean_outcome"]][model_values_all[["int_CBT_scaled_mean_outcome"]][,"ENSG"] %in% Sznajder_blood[,"ENSG"],]
Sznajder_blood <- Sznajder_blood[Sznajder_blood[,"ENSG"] %in% model_values_all[["int_CBT_scaled_mean_outcome"]][,"ENSG"],]

```
## Scatter plot
```{r}
df <- data.frame(Response = model_values_all[["int_CBT_scaled_mean_outcome"]][,"Estimate"],
                 Sznajder_blood = Sznajder_blood[,"Estimate"],
                 gene = Sznajder_blood[,"ENSG"])
df$intersect <- df$gene %in% intersect(int_hits, V2Mode_hits)
df <- df[order(df$intersect),]

ggplot(df,  aes_string(x="Sznajder_blood", y="Response")) + 
  geom_point(col = ifelse(df$intersect == "TRUE", "purple4", "grey"), cex = ifelse(df$intersect == "TRUE", 0.4, 0.3))+
  ggtitle("")+
  xlab("DM1 Effect (logCPM)") + 
  ylab("Association with response (logCPM/Stdev)") +
  geom_hline(yintercept=0, col = "red")+
  geom_vline(xintercept=0, col = "red")+
  scale_y_continuous(breaks = seq(-3, 3, 1), 
                     labels = scales::comma(seq(-3, 3, 1), accuracy = c(1)), 
                     limits = c(-3, 3),
                     sec.axis = dup_axis(breaks = derive(), labels = NULL, name = NULL))+
  scale_x_continuous(breaks = seq(-3, 3, 1), 
                     labels = scales::comma(seq(-3, 3, 1), accuracy = c(1)), 
                     limits = c(-3, 3),
                     sec.axis = dup_axis(breaks = derive(), labels = NULL, name = NULL))+
  theme_classic() +
  theme(panel.grid.major.x = element_line(size = 0.25, color = "grey"))+
  theme(panel.grid.major.y = element_line(size = 0.25, color = "grey"))

ggsave("Z:/Analysis_projects/RvC_recognition_rnaseq_diff_expr/for_paper_counts/Figs_for_paper/FigS3_sznajder_CBT.png", dpi =600, height = 5, width = 7)

#how many genes covered in both?
length(overlap_genes)

# how many in same direction?
print(length(overlap_genes) - sum(
  sum(df$Response[df$intersect == "TRUE"] > 0 & df$Sznajder_blood[df$intersect == "TRUE"] > 0), 
  sum(df$Response[df$intersect == "TRUE"] < 0 & df$Sznajder_blood[df$intersect == "TRUE"] < 0)))

```

