---
title: "FigS2_scatter_otherstudies"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(readxl)
library(tidyverse)
library(cowplot)
library(stats)
library(gplots)
```

## Fig S2

## loading data 
```{r}
hgnc_symbol <- read.table("Z:/Analysis_projects/RvC_recognition_rnaseq_diff_expr/Analyses_rnaseq_recognition/metadata/ENSG_geneSymbol2.txt", sep =",", header=TRUE)
load(file = "Z:/Analysis_projects/RvC_recognition_rnaseq_diff_expr/for_paper_counts/fits_paper/model_values_all.RData")
Sznajder_blood <- read.csv(file = "Z:/Analysis_projects/GSE138691/lm_fit_disease_values.csv", sep = " ")
Charlet_heart <- read.csv(file = "Z:/Knowledge_base/DM_T_003/lm_fit_disease_values.csv", sep = " ")
Wang_brain <- read.csv(file = "Z:/Knowledge_base/DM_T_041/lm_fit_disease_values.csv", sep = " ")
Wang_MBNLinf <- read_excel("Z:/Knowledge_base/DM_T_007/Kallisto_table_s5_ddy432.xlsx")

model_values_S2 <- read.csv(file = "Z:/Analysis_projects/RvC_recognition_rnaseq_diff_expr/for_paper_counts/Figs_for_paper/TableS2_effects_105genes.csv", sep = ",")


```

### Data prep
```{r}
Wang_MBNLinf <- inner_join(hgnc_symbol, Wang_MBNLinf, by = c("hgnc_symbol" = "Gene"))
colnames(Wang_MBNLinf)[colnames(Wang_MBNLinf) == "ensembl_gene_id"] <- "ENSG"
colnames(Wang_MBNLinf)[colnames(Wang_MBNLinf) == "Correlation to MBNLinf"] <- "Estimate"

studies <- list("Sznajder_blood" = Sznajder_blood, 
                "Charlet_heart" = Charlet_heart,
                "Wang_brain" = Wang_brain,
                "Wang_MBNLinf" = Wang_MBNLinf 
)
```


## Scatter plot

```{r}
study_plots <- list()
for (study in names(studies)){

df <- data.frame(cbind(model_values_all[["V2Mode"]][,"Estimate"][model_values_all[["V2Mode"]][,"ENSG"] %in% 
                                                                   intersect(model_values_all[["V2Mode"]][,"ENSG"],
                                                                             studies[[study]][,"ENSG"])])*100,
studies[[study]][,"Estimate"][studies[[study]][,"ENSG"] %in% 
                                                                   intersect(model_values_all[["V2Mode"]][,"ENSG"],
                                                                             studies[[study]][,"ENSG"])])
colnames(df) <- c("ReCognitION", study)

study_plots[[study]] <- ggplot(df,  aes_string(x="ReCognitION", y = study)) + 
  geom_point(cex = 0.5)+
  ggtitle(paste(gsub("_", " ", study))) +
  theme(legend.position = "none", aspect.ratio = 1/1) +
  xlab("Repeat length effect ReCognitION (logCPM/100CTG)") + 
  ylab(ifelse(study == "Wang_MBNLinf", "Correlation to MBNLinf", paste("DM1 effect (logCPM)"))) +
  geom_hline(yintercept=0, col = "red")+
  geom_vline(xintercept=0, col = "red") +
  annotation_custom(grobTree(textGrob(
    paste0("Rho = ", round(cor.test(df[,"ReCognitION"],df[,study])$estimate, 3)), 
    x=0.05, y=0.95, just = "left")))+
  scale_x_continuous(labels = scales::comma(seq(-0.6, 0.6, 0.2), accuracy = 0.1), 
                     breaks = seq(-0.6, 0.6, 0.2), 
                     lim = c(-0.6, 0.6),
                     sec.axis = dup_axis(breaks = derive(), labels = NULL, name = NULL))+
  scale_y_continuous(lim = c(-max(abs(df[, study])), max(abs(df[, study]))),
                     sec.axis = dup_axis(breaks = derive(), labels = NULL, name = NULL))+
  theme_classic() +
  theme(panel.grid.major.x = element_line(size = 0.25, color = "grey"))+
  theme(panel.grid.major.y = element_line(size = 0.25, color = "grey")
)
}

study_plots <- plot_grid(plotlist = study_plots, ncol = 2 )
ggsave(study_plots, file = "Z:/Analysis_projects/RvC_recognition_rnaseq_diff_expr/for_paper_counts/Figs_for_paper/FigS2_studyPlots.png", height = 10, width = 10, dpi = 600 )
```