---
title: "Fig1_outcomes"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Fig S1


```{r}
load(file = "Z:/Analysis_projects/RvC_recognition_rnaseq_diff_expr/Analyses_rnaseq_recognition/samples.RData")
```

## plot
```{r}
df <- data.frame(CTGlength = as.numeric(samples$V2Mode[samples$Visit == "V2"]))

print(ggplot(df, aes(x = CTGlength))+
               geom_histogram(binwidth =50)+

  xlab("Modal CTG repeat length")+
  ylab("Number of patients")+
  scale_x_continuous(limits = c(0,1000), breaks=seq(0,1000,100)) 
)
ggsave(file = "Z:/Analysis_projects/RvC_recognition_rnaseq_diff_expr/for_paper_counts/Figs_for_paper/FigS1_CTGs.png")


df2 <- data.frame(Sex = samples$Sex[samples$Visit == "V2"], Age = as.numeric(samples$AgeBaseline[samples$Visit == "V2"])) 

print(ggplot(df2, aes(x = Sex, y = Age))+
               geom_dotplot(binaxis = "y", binwidth = 1, stackdir = "center")+
  xlab("Sex")+
  ylab("Age in years")+
  scale_y_continuous(limits = c(0,70),breaks=seq(0,70,10)) 
)
ggsave(file = "Z:/Analysis_projects/RvC_recognition_rnaseq_diff_expr/for_paper_counts/Figs_for_paper/FigS1_AgeSex.png")
```
